[workspace]
resolver = "3"
members = ["ast", "crates/bevy_pipe_core", "demo/bomberman/engine/bevy", "demo/rail_dispatch/engine/bevy", "demo/fireworks/engine/bevy", "demo/village/engine/bevy", "demo/airtrain/engine/bevy"]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.85"
